name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['22.3.4.21', '23.0.2', '24.1.3', '25.1.1']
        rebar3: ['3.20.0']
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
        version-type: strict
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 eunit
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run xref
      run: rebar3 xref
